ip_forward: true
player_limit: -1
network_compression_threshold: 256
stats: b9bd0bca-8629-446e-982d-500e8db265de
groups:
  UnstableTNT:
  - admin
servers:
  Factions:
    motd: PMC167daa5f41adda456f0fa03ea054fb49
    address: localhost:25555
    restricted: false
  TD:
    motd: \u00A75\u00A7n\u00A7kTNT\u00A7r \u00A74Unstable\u00A7cT\u00A7fN\u00A7cT\u00A74s \u00A7bSky\u00A74Wars \u00A75\u00A7n\u00A7kTNT\u00A7r
    address: localhost:25556
    restricted: false
  SkyBlock:
    motd: \u00A75\u00A7n\u00A7kTNT\u00A7r \u00A74Unstable\u00A7cT\u00A7fN\u00A7cT\u00A74s \u00A7bSky\u00A72Block \u00A75\u00A7n\u00A7kTNT\u00A7r
    address: localhost:25557
    restricted: false
  Factions_1.9:
    address: localhost:25560
    restricted: false
    motd: '&5Kit&4PVP'
  Paintball:
    address: localhost:25566
    restricted: false
    motd: '&4Ultra Hardcore'
  Hub:
    address: localhost:25569
    restricted: false
    motd: '&4Ultra Hardcore'
  OP Factions:
    address: localhost:26999
    restricted: false
    motd: '&4Parkour'
  Prison:
    address: localhost:29999
    restricted: false
    motd: '&4Prison'
  ColorShuffle:
    address: localhost:29875
    restricted: false
    motd: '&4EggWars'
  SurvivalGames:
    address: localhost:26456
    restricted: false
    motd: '&4SG'
  SkyWars:
    address: localhost:25597
    restricted: false
    motd: '&4SKyWars'
  BedWars:
    address: localhost:26399
    restricted: false
    motd: '&4BedWars'
  Creative:
    address: localhost:25589
    restricted: false
    motd: '&4Creative'
  Survival_1.9:
    address: localhost:25588
    restricted: false
    motd: '&4Survival for 1.9'
  KitPVP:
    address: localhost:12789
    restricted: false
    motd: '&4KitPVP'
  MobRunner:
    address: localhost:54325
    restricted: false
    motd: '&4MobRunner'
timeout: 30000
admin: -UnstableTNT
listeners:
- query_port: 35555
  motd: PMC167daa5f41adda456f0fa03ea054fb49
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  bind_local_address: true
  host: 192.168.200.189:25565
  max_players: 1500
  tab_size: 100
  force_default_server: true
  priorities:
  - Hub
  - Hub
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bukkit.command.op
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bukkit.command.op
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
